name: flutter_one_pass
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/Mzrong/flutter_one_pass

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: life.zrong.flutter_one_pass
        pluginClass: FlutterOnePassPlugin
      ios:
        pluginClass: FlutterOnePassPlugin
